/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kffekko_report.ui;

import com.kffekko_report.mysql.models.Montant;
import com.kffekko_report.mysql.models.Poids;
import com.kffekko_report.util.DialogFile;
import com.kffekko_report.util.ExcelFile;
import com.kffekko_report.util.FileChooser;
import com.kffekko_report.util.FileUtils;
import java.awt.Dialog.ModalityType;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author akil
 */
public class ImportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImportPanel
     */
    public ImportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btFileSelect = new javax.swing.JButton();
        btImportSql = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btImportExcel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbFileSelected = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        btFileSelect.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        btFileSelect.setText("Selectionner fichier");
        btFileSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFileSelectMouseClicked(evt);
            }
        });
        btFileSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFileSelectActionPerformed(evt);
            }
        });

        btImportSql.setBackground(new java.awt.Color(224, 224, 224));
        btImportSql.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btImportSqlMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btImportSqlMouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel1.setText("<html>importer votre <br/> fichier sql</html>");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sql.png"))); // NOI18N

        javax.swing.GroupLayout btImportSqlLayout = new javax.swing.GroupLayout(btImportSql);
        btImportSql.setLayout(btImportSqlLayout);
        btImportSqlLayout.setHorizontalGroup(
            btImportSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btImportSqlLayout.createSequentialGroup()
                .addGroup(btImportSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btImportSqlLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btImportSqlLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btImportSqlLayout.setVerticalGroup(
            btImportSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btImportSqlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btImportExcel.setBackground(new java.awt.Color(224, 224, 224));
        btImportExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btImportExcelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btImportExcelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btImportExcelMouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel2.setText("<html>importer votre <br />fichier excel</html>");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/excel.png"))); // NOI18N

        javax.swing.GroupLayout btImportExcelLayout = new javax.swing.GroupLayout(btImportExcel);
        btImportExcel.setLayout(btImportExcelLayout);
        btImportExcelLayout.setHorizontalGroup(
            btImportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btImportExcelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(btImportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btImportExcelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btImportExcelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        btImportExcelLayout.setVerticalGroup(
            btImportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btImportExcelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        lbFileSelected.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        lbFileSelected.setText("Entrer le nom de la feuille excel");
        lbFileSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbFileSelectedActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel5.setText("Fichier");

        jComboBox1.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "excel" }));

        jLabel6.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel6.setText("Nom de la feuille ");

        jLabel7.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel7.setText("Quel type de fichier avez vous ? ");

        jLabel8.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel8.setText("<html><p>Téléverser votre fichier excel, choisissez la feuille de calcul avec les données, cliquez sur Importer fichier. Nous importerons votre fichier excel dans votre BD</p></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btImportSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btImportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lbFileSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(btFileSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFileSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFileSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btImportSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btFileSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFileSelectMouseClicked
        // TODO add your handling code here:
        
        JFileChooser choix = new JFileChooser();
        int retour = choix.showOpenDialog(this);
        if(retour==JFileChooser.APPROVE_OPTION){
            
            String s  = choix.getSelectedFile().getAbsolutePath();
            FileUtils file = new FileUtils(s);
            try {
                file.moveInDirectory("./docs/");
            } catch (IOException ex) {
                Logger.getLogger(ImportPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
            // un fichier a été choisi (sortie par OK)
            // nom du fichier  choisi 
            String name = choix.getSelectedFile().getName();
            this.fileUrl = "./docs/" + name;
            
           
            //Object body[][] = excel.getBody();
         
            
            /*for(int i = 0; i < body.length; i++){
                for(int j = 0; j < body[i].length; j++){
                    System.out.println(body[i][j]);  
                }
            }*/
            // chemin absolu du fichier choisi
            //String s  = choix.getSelectedFile().getAbsolutePath();
            
            /*lbFileSelected.setText(s);
            repaint();
            revalidate();*/
            /*FileUtils file = new FileUtils(s);
            try {
                file.moveInDirectory("./docs/");
            } catch (IOException ex) {
                Logger.getLogger(ImportPanel.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            
            
        }
    }//GEN-LAST:event_btFileSelectMouseClicked

    private void btFileSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFileSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFileSelectActionPerformed

    private void lbFileSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbFileSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbFileSelectedActionPerformed

    private void btImportSqlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportSqlMouseEntered
        // TODO add your handling code here:
        //btImportSql.setBackground(new java.awt.Color(252, 255, 250));
    }//GEN-LAST:event_btImportSqlMouseEntered

    private void btImportSqlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportSqlMouseExited
        // TODO add your handling code here:
        // btImportSql.setBackground(new java.awt.Color(224, 224, 224));
    }//GEN-LAST:event_btImportSqlMouseExited

    private void btImportExcelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportExcelMouseEntered
        // TODO add your handling code here:
        btImportExcel.setBackground(new java.awt.Color(252, 255, 250));
    }//GEN-LAST:event_btImportExcelMouseEntered

    private void btImportExcelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportExcelMouseExited
        // TODO add your handling code here:
        btImportExcel.setBackground(new java.awt.Color(224, 224, 224));
    }//GEN-LAST:event_btImportExcelMouseExited

    private void btImportExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportExcelMouseClicked
        // TODO add your handling code here:
        System.out.println(this.fileUrl);
        System.out.println(this.lbFileSelected.getText());
        
        String sheetName = this.lbFileSelected.getText();
        if("POIDS F01".equals(sheetName)){
            try {
                ExcelFile excel = new ExcelFile(this.fileUrl, this.lbFileSelected.getText());
                Object body[][] = excel.getBody();
                
                for (Object[] body1 : body) {
                Poids poids = new Poids((String[]) body1);
                try {
                poids.save();
                } catch (SQLException ex) {
                Logger.getLogger(ImportPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
            } catch (IOException ex) {
                Logger.getLogger(ImportPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if("MONTANTS F01".equals(sheetName)){
            try {
                ExcelFile excel = new ExcelFile(this.fileUrl, sheetName);
                Object body[][] = excel.getBody();
                
                for (Object[] body1 : body) {
                    Montant montant = new Montant((String[]) body1);
                    try {
                        montant.save();
                    } catch (SQLException ex) {
                        Logger.getLogger(ImportPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(ImportPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
            
    }//GEN-LAST:event_btImportExcelMouseClicked


    private String fileUrl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btFileSelect;
    private javax.swing.JPanel btImportExcel;
    private javax.swing.JPanel btImportSql;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lbFileSelected;
    // End of variables declaration//GEN-END:variables

    private void Poids(Object[] object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
