/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kffekko_report.ui;

import com.kffekko_report.jasperreport.BuildReport;
import com.kffekko_report.jasperreport.ExportFile;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author akil
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        periodStartSB = new javax.swing.JComboBox();
        periodEndSB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modelTypesSB = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btImportSql = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btImportExcel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        citiesSB = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        typesProductSB = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        productSB = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        categories = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        typeExportateurs = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        speExportateurs = new javax.swing.JList<>();
        yearStart = new javax.swing.JComboBox<>();
        yearEnd = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        periodStartSB.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        periodStartSB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout ", "Septembre", "Octobre", "Novembre", "Decembre" }));

        periodEndSB.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        periodEndSB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout ", "Septembre", "Octobre", "Novembre", "Decembre" }));

        jLabel2.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel2.setText("De");

        jLabel4.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel4.setText("Modèle");

        modelTypesSB.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        modelTypesSB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INTRODUCTION : REFERENTIEL DE DONNEES REELEMENT PESEES & CONSTATEES A L'EXPORT", "I.1 LA CERTIFICATION DES PESEES A L'EXPORT", "I.2 L'ACTIVITE DE CONTROLE DES POIDS DECLARES ET DE PESAGES DES FEVES", "I.3 PRELEVEMENTS ET REAJUSTEMENTS DE TAXES SUR LES FEVES", "I.4 GROUPES EXPORTATEURS", "I.5 LES PESEES A L'EXPORT DES FEVES", "I.6 LA CERTTIFICATION A L EXPORT DES PESEE DE SEMI-FINIS", "I.7 LES TRANSITAIRES", "I.8 LES BANQUES", "I.9 LES DESTINATIONS" }));
        modelTypesSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTypesSBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel5.setText("Type de produit(s)");

        jLabel10.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel10.setText("Port(s) d'embarquement");

        btImportSql.setBackground(new java.awt.Color(224, 224, 224));
        btImportSql.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btImportSqlMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btImportSqlMouseEntered(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N

        javax.swing.GroupLayout btImportSqlLayout = new javax.swing.GroupLayout(btImportSql);
        btImportSql.setLayout(btImportSqlLayout);
        btImportSqlLayout.setHorizontalGroup(
            btImportSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btImportSqlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        btImportSqlLayout.setVerticalGroup(
            btImportSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btImportSqlLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(17, 17, 17))
        );

        btImportExcel.setBackground(new java.awt.Color(224, 224, 224));
        btImportExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btImportExcelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btImportExcelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btImportExcelMouseEntered(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/word.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btImportExcelLayout = new javax.swing.GroupLayout(btImportExcel);
        btImportExcel.setLayout(btImportExcelLayout);
        btImportExcelLayout.setHorizontalGroup(
            btImportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btImportExcelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        btImportExcelLayout.setVerticalGroup(
            btImportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btImportExcelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(14, 14, 14))
        );

        citiesSB.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        citiesSB.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tous", "Abidjan", "San pedro" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        citiesSB.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        citiesSB.setSelectedIndices(new int[] {0});
        jScrollPane1.setViewportView(citiesSB);

        typesProductSB.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        typesProductSB.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tous", "Fèves", "Fèves semi-fini", "Vertes" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        typesProductSB.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        typesProductSB.setToolTipText("");
        typesProductSB.setSelectedIndices(new int[] {0});
        jScrollPane2.setViewportView(typesProductSB);

        jLabel6.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel6.setText("Produit");

        productSB.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        productSB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cacao", "Cafe" }));
        productSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSBActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel11.setText("Categorie(s)");

        categories.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        categories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "TOUS", "TRANSFORMATEUR", "NON TRANSFORMATEUR" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        categories.setSelectedIndices(new int[] {0});
        jScrollPane3.setViewportView(categories);

        jLabel16.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel16.setText("Type exportateur(s)");

        typeExportateurs.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        typeExportateurs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "TOUS", "MULTINATIONALE", "NATIONALE" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        typeExportateurs.setSelectedIndices(new int[] {0});
        jScrollPane4.setViewportView(typeExportateurs);

        jLabel17.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel17.setText("Specificité exportateur(s)");

        speExportateurs.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        speExportateurs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "TOUS", "COOPEX", "PMEX" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        speExportateurs.setSelectedIndices(new int[] {0});
        jScrollPane5.setViewportView(speExportateurs);

        yearStart.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        yearStart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020" }));
        yearStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearStartActionPerformed(evt);
            }
        });

        yearEnd.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        yearEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020" }));
        yearEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearEndActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel7.setText("A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btImportSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btImportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(periodStartSB, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(periodEndSB, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productSB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelTypesSB, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodStartSB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodEndSB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelTypesSB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btImportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImportSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btImportSqlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportSqlMouseExited
        // TODO add your handling code here:
        btImportSql.setBackground(new java.awt.Color(224, 224, 224));
    }//GEN-LAST:event_btImportSqlMouseExited

    private void btImportSqlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportSqlMouseEntered
        // TODO add your handling code here:
        btImportSql.setBackground(new java.awt.Color(252, 255, 250));
    }//GEN-LAST:event_btImportSqlMouseEntered

    private void btImportExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportExcelMouseClicked
        BuildReport report = new BuildReport(
                this.periodStartSB.getSelectedItem().toString(),
                this.yearStart.getSelectedItem().toString(),
                this.periodEndSB.getSelectedItem().toString(),
                this.yearEnd.getSelectedItem().toString(),
                this.productSB.getSelectedItem().toString(), 
                this.typesProductSB.getSelectedValuesList(),
                this.citiesSB.getSelectedValuesList(),
                this.categories.getSelectedValuesList(),
                this.typeExportateurs.getSelectedValuesList(),
                this.speExportateurs.getSelectedValuesList(),
                this.modelTypesSB.getSelectedItem().toString()
        );
        try {
            report.exportModel();
        } catch (IOException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btImportExcelMouseClicked

    private void btImportExcelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportExcelMouseExited
        // TODO add your handling code here:
        btImportExcel.setBackground(new java.awt.Color(224, 224, 224));
    }//GEN-LAST:event_btImportExcelMouseExited

    private void btImportExcelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btImportExcelMouseEntered
        // TODO add your handling code here:
        btImportExcel.setBackground(new java.awt.Color(252, 255, 250));
    }//GEN-LAST:event_btImportExcelMouseEntered

    private void modelTypesSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTypesSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTypesSBActionPerformed

    private void productSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productSBActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void yearStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearStartActionPerformed

    private void yearEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btImportExcel;
    private javax.swing.JPanel btImportSql;
    private javax.swing.JList<String> categories;
    private javax.swing.JList<String> citiesSB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox modelTypesSB;
    private javax.swing.JComboBox periodEndSB;
    private javax.swing.JComboBox periodStartSB;
    private javax.swing.JComboBox productSB;
    private javax.swing.JList<String> speExportateurs;
    private javax.swing.JList<String> typeExportateurs;
    private javax.swing.JList<String> typesProductSB;
    private javax.swing.JComboBox<String> yearEnd;
    private javax.swing.JComboBox<String> yearStart;
    // End of variables declaration//GEN-END:variables
}
